package cz.cvut.fel.bp.deckservice.mapper;

import cz.cvut.fel.bp.deckservice.dto.deck.DeckDetailsResponseDTO;
import cz.cvut.fel.bp.deckservice.dto.deck.DeckRequestDTO;
import cz.cvut.fel.bp.deckservice.dto.deck.DeckSummaryResponseDTO;
import cz.cvut.fel.bp.deckservice.model.Deck;
import org.mapstruct.Builder;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

/**
 * Mapper for converting between Deck entities and their corresponding DTOs.
 * Using MapStruct to automatically generate the implementation of this interface.
 */
@Mapper(componentModel = "spring", uses = {QuestionMapper.class}, builder = @Builder(disableBuilder = true))
public interface DeckMapper {

    /**
     * Converts a Deck entity to its corresponding DeckResponseDTO.
     * @param deck the Deck entity to be converted
     * @return the corresponding DeckResponseDTO, including a count of how many users have favorited this deck
     */
    @Mapping(target = "favoritesCount", // Info: ONLY COUNT of users who have favorited this deck
            expression = "java(deck.getFavoritedByUsers() != null ? deck.getFavoritedByUsers().size() : 0)")
    DeckDetailsResponseDTO deckToDetailsResponse(Deck deck);

    /**
     * Converts a Deck entity to its corresponding DeckResponseDTO.
     * @param deck the Deck entity to be converted
     * @return the corresponding DeckSummaryResponseDTO, including a count of how many users have favorited this deck
     */
    @Mapping(target = "favoritesCount", // Info: ONLY COUNT of users who have favorited this deck
            expression = "java(deck.getFavoritedByUsers() != null ? deck.getFavoritedByUsers().size() : 0)")
    @Mapping(target = "numberOfQuestions",
            expression = "java(deck.getQuestions() != null ? deck.getQuestions().size() : 0)")
    @Mapping(target = "authorName", source = "authorName")
    DeckSummaryResponseDTO deckToSummaryResponse(Deck deck, String authorName);

    /**
     * Converts a DeckRequestDTO to a Deck entity.
     * Warn: Ignoring fields that should not be updated by USER.
     * @param request the source DTO containing the data for the new Deck
     * @return a new Deck entity populated with values from the request DTO
     */
    @Mapping(target = "id", ignore = true) // ID generated by database
    @Mapping(target = "authorId", ignore = true) // Author ID set in service layer based on authenticated user
    @Mapping(target = "questions", ignore = true) // Set separately
    @Mapping(target = "favoritedByUsers", ignore = true) // Set by different endpoint
    @Mapping(target = "createdAt", ignore = true) // Set by @PrePersist in model
    @Mapping(target = "updatedAt", ignore = true) // Set by @PrePersist in model
    Deck deckRequestToDeck(DeckRequestDTO request);

    /**
     * Updates an existing Deck entity with values from a DeckRequestDTO.
     * Warn: Ignoring fields that should not be updated by USER.
     * @param request the source DTO containing updated values
     * @param deck the target entity to be updated
     */
    @Mapping(target = "id", ignore = true) // ID generated by database
    @Mapping(target = "authorId", ignore = true) // Author ID set in service layer based on authenticated user
    @Mapping(target = "questions", ignore = true) // Set separately
    @Mapping(target = "favoritedByUsers", ignore = true) // Set by different endpoint
    @Mapping(target = "createdAt", ignore = true) // Set by @PrePersist in model
    @Mapping(target = "updatedAt", ignore = true) // Set by @PrePersist in model
    void updateDeckFromRequest(DeckRequestDTO request, @MappingTarget Deck deck);
}
