package cz.cvut.fel.bp.deckservice.mapper;

import cz.cvut.fel.bp.deckservice.dto.question.QuestionRequestDTO;
import cz.cvut.fel.bp.deckservice.dto.question.QuestionResponseDTO;
import cz.cvut.fel.bp.deckservice.model.Question;
import org.mapstruct.Builder;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

/**
 * Mapper for converting between Question entities and their corresponding DTOs.
 * Using MapStruct to automatically generate the implementation of this interface.
 */
@Mapper(componentModel = "spring", uses = {AnswerMapper.class}, builder = @Builder(disableBuilder = true))
public interface QuestionMapper {

    /**
     * Converts a Question entity to its corresponding QuestionResponseDTO.
     * @param question the Question entity to be converted
     * @return the corresponding QuestionResponseDTO
     */
    QuestionResponseDTO toResponse(Question question);

    /**
     * Converts a QuestionRequestDTO to a Question entity.
     * @param request the source DTO containing the data for the new Question
     * @return a new Question entity populated with values from the request DTO
     */
    @Mapping(target = "id", ignore = true)         // ID generated by database
    @Mapping(target = "deck", ignore = true)       // Deck association is set separately
    @Mapping(target = "answers", ignore = true)    // Answers are set separately
    Question toEntity(QuestionRequestDTO request);

    /**
     * Updates an existing Question entity with values from a QuestionRequestDTO.
     * @param request the source DTO containing updated values
     * @param question the target entity to be updated
     */
    @Mapping(target = "id", ignore = true)         // ID generated by database
    @Mapping(target = "deck", ignore = true)       // Deck association is set separately
    @Mapping(target = "answers", ignore = true)    // Answers are set separately
    void updateEntityFromDTO(QuestionRequestDTO request, @MappingTarget Question question);
}
