spring:
  application:
    name: FlashcardsServiceApplication
  datasource:
    url: ${DB_URL}${FLASHCARDS_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.batch_size: 50 # num of insert/update statements to send in one batch
        order_inserts: true
        order_updates: true
    show-sql: false
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

app:
  security:
    # Custom JWT
    jwt:
      secret: ${JWT_SECRET} # at least 256 bits / 32 characters

microservices:
  deck-service:
    url: ${DECK_SERVICE_URL}

flashcards:
  spaced-repetition:
    rules:
      AGAIN:
        multiplier: 0.0
        min-days: 0
      HARD:
        multiplier: 1.2
        min-days: 1
      GOOD:
        multiplier: 2.5
        min-days: 1
      EXCELLENT:
        multiplier: 3.5
        min-days: 4

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
    instances:
      deckService:
        baseConfig: default
      rabbitPublisher:
        slidingWindowSize: 5
        failureRateThreshold: 80

logging:
  level:
    root: INFO