package cz.cvut.fel.bp.userservice.mapper;

import cz.cvut.fel.bp.userservice.dto.UserInfoDTO;
import cz.cvut.fel.bp.userservice.dto.UserRegistrationRequestDTO;
import cz.cvut.fel.bp.userservice.dto.UserResponseDTO;
import cz.cvut.fel.bp.userservice.dto.UserUpdateRequestDTO;
import cz.cvut.fel.bp.userservice.security.UserPrincipal;
import cz.cvut.fel.bp.userservice.model.User;
import org.mapstruct.Builder;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

/**
 * Mapper for converting between User entities and their corresponding DTOs.
 * Using MapStruct to automatically generate the implementation of this interface.
 */
@Mapper(componentModel = "spring", builder = @Builder(disableBuilder = true))
public interface UserMapper {

    /**
     * Converts User entity to a DTO that is sent to the client.
     * @param user User entity from DB
     * @return User response DTO
     */
    UserResponseDTO userToUserResponse(User user);

    /**
     * Converts User entity to internal user-info DTO.
     * @param user User entity from DB
     * @return User info DTO
     */
    @Mapping(target = "role", expression = "java(user.getRole().name())")
    UserInfoDTO userToUserInfo(User user);

    /**
     * Converts User entity to principal used in security.
     * @param userFromOIDC User entity from db requested by OIDC
     * @return principal used in security
     */
    UserPrincipal userToUserPrincipal(User userFromOIDC);

    /**
     * Converts User principal from security to a DTO that is used among microservices for security.
     * @param principal User principal from security
     * @return User info DTO
     */
    UserInfoDTO userPrincipalToUserInfo(UserPrincipal principal);

    /**
     * Converts User principal to a response DTO. Role is derived from the principal.role() string
     * and converted to the enum using a tolerant helper.
     * @param principal User principal from security
     * @return User response DTO
     */
    /**
     * Map principal to response DTO. Implemented as a default method to ensure
     * the conversion from principal.role() string to UserRole uses the
     * tolerant fromString(...) helper and avoids generated Enum.valueOf calls.
     */
    default UserResponseDTO userPrincipalToUserResponse(UserPrincipal principal) {
        if (principal == null) return null;

        return UserResponseDTO.builder()
                .id(principal.id())
                .username(principal.username())
                .email(principal.email())
                .role(cz.cvut.fel.bp.userservice.model.UserRole.fromString(principal.role()))
                .build();
    }

    /**
     * Converts registration DTO to User entity.
     * @param dto Registration sent by the client
     * @return User entity
     */
    @Mapping(target = "id", ignore = true)             // ID generated by database
    @Mapping(target = "role", ignore = true)           // Role is set separately
    @Mapping(target = "quizHistories", ignore = true)  // Quiz history is handled separately
    @Mapping(target = "oidcSubject", ignore = true)
    User registrationToUser(UserRegistrationRequestDTO dto);

    /**
     * Converts user details to User entity that will be saved.
     * @param username username of the user
     * @param email email of the user
     * @param oidcSubject OIDC subject used for registration
     * @return User entity
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "role", ignore = true)
    @Mapping(target = "quizHistories", ignore = true)
    User oidcRegistrationToUser(String username, String email, String oidcSubject);

    /**
     * Updates user info from the given DTO. Only username and email are updated; other fields are ignored.
     * @param dto DTO of updated user info (username, email)
     * @param user User entity from DB
     */
    @Mapping(target = "id", ignore = true)             // ID generated by database
    @Mapping(target = "role", ignore = true)           // Role is not updated here
    @Mapping(target = "quizHistories", ignore = true)  // Quiz history is handled separately
    @Mapping(target = "oidcSubject", ignore = true)
    void updateUserFromDTO(UserUpdateRequestDTO dto, @MappingTarget User user);
}
