events {
    worker_connections 1024;
}

http {

    map $cookie_jwt_token $auth_header {
        ""      ""; 
        default "Bearer $cookie_jwt_token";
    }

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_set_header X-Forwarded-Proto https;

    proxy_set_header Authorization $auth_header;

    server {

      #add_header Content-Security-Policy "default-src 'self';script-src 'self' 'unsafe-eval' https://accounts.google.com;style-src 'self' 'unsafe-inline';img-src 'self' data: https:;frame-src https://accounts.google.com;connect-src 'self';font-src 'self' data:;object-src 'none';base-uri 'self';form-action 'self';" always;
      add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://accounts.google.com https://auth.privy.io; frame-src 'self' https://accounts.google.com https://auth.privy.io; connect-src 'self' https://accounts.google.com https://auth.privy.io https://outrank-headwear-tremble.ngrok-free.dev wss://outrank-headwear-tremble.ngrok-free.dev; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;" always;

        listen 80;

        server_name _;

        location /api/internal {
            deny all;
            return 404;
        }

        location /api/auth {
            proxy_pass http://user-service:8080/api/auth;
        }

        location /api/users {
            proxy_pass http://user-service:8080/api/users;
        }

        location /api/decks {
            proxy_pass http://deck-service:8080/api/decks;
        }

        location /api/flashcards {
            proxy_pass http://flashcards-service:8080/api/flashcards;
        }

        location /api/quiz {
            proxy_pass http://quiz-service:8080/api/quiz;
        }

        location /ws-quiz {
            proxy_pass http://quiz-service:8080/ws-quiz;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            proxy_buffering off;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header Authorization $auth_header;

            proxy_set_header Authorization $auth_header;

            proxy_read_timeout 86400;
            proxy_send_timeout 86400;
        }
    }
}
