name: Enforce Source Branch

on:
  pull_request:
    branches: [ "main" ]

jobs:
  verify-source:
    runs-on: ubuntu-latest
    steps:
      - name: Source branch check
        if: github.head_ref != 'dev'
        run: |
          echo "::error:: Only the dev branch can be merged into main."
          exit 1
